name: OSV.dev Dependency Review
on:
 - pull_request
permissions:
  actions: read
  pull-requests: write
  contents: read
  security-events: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: google/osv-scanner-action@v2.3.5
